import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { TSample } from '@/types/TSample'
import { useEffect, useState } from 'react'
import DataView from '@/components/DataView'

// import SampleChart from '@/components/SampleChart'
import dynamic from 'next/dynamic'
const DynamicSampleChart = dynamic(() => import('@/components/SampleChart'), { ssr: false })

const Home: NextPage = () => {
  const [rawData, setRawData] = useState<TSample[]>([])

  const getRandomValue = (min: number, max: number): number => {
    const diff = max - min
    return min + Math.floor(Math.random() * diff)
  }

  const getRandomSample = (date: Date): TSample => {
    return {
      date,
      suggest1: getRandomValue(10, 20),
      suggest2: getRandomValue(10, 20),
      suggest3: getRandomValue(10, 20),
      delivery1: getRandomValue(10, 20),
      delivery2: getRandomValue(10, 20),
      delivery3: getRandomValue(10, 20),
      sale1: getRandomValue(10, 20),
      sale2: getRandomValue(10, 20),
      sale3: getRandomValue(10, 20),
      disposal1: getRandomValue(0, 3),
      disposal2: getRandomValue(0, 3),
      disposal3: getRandomValue(0, 3),
      memo: '',
    }
  }

  const changeData = () => {
    const list: TSample[] = []
    for (let i = 0; i < 7; i++) {
      list.push(getRandomSample(new Date(2022, 4, i + 1)))
    }
    setRawData(list)
  }

  useEffect(() => {
    changeData()
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <button onClick={changeData}>データ変更</button>
        <DynamicSampleChart data={rawData} />
        <hr />
        <DataView data={rawData} />
      </main>

      <footer className={styles.footer}>Sample</footer>
    </div>
  )
}

export default Home
